version: '3.8'

services:
  backend:
    build:
      context: ./study_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/study?useUnicode=true&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

    depends_on:
      - db

  frontend:
    build:
      context: ./study_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: study
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
      - ./study.sql:/docker-entrypoint-initdb.d/study.sql

volumes:
  db_data:
